title: Mi sitio con Minimal Mistakes
theme: minimal-mistakes-jekyll

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-coffeescript

# Opcional: para activar la skin oscura
minimal_mistakes_skin: "dark"
